"""
Email notifier — sends a formatted digest of jobs requiring manual application.
Uses Python stdlib smtplib; auto-selects STARTTLS (port 587) or SSL (port 465).
"""
from __future__ import annotations

import logging
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List

from src.config import EmailConfig

logger = logging.getLogger(__name__)


class Notifier:
    def __init__(self, config: EmailConfig) -> None:
        self._cfg = config

    def send_manual_apply_digest(self, jobs: List[dict]) -> bool:
        """
        Send a digest email listing all jobs that need manual application.
        Returns True on success, False on any failure (logs error, never raises).
        """
        if not self._cfg.enabled:
            logger.info("Email notifications disabled — skipping digest.")
            return True

        if not jobs:
            logger.info("No manual-apply jobs to notify about.")
            return True

        try:
            msg = self._build_message(jobs)
            return self._send(msg)
        except Exception as exc:
            logger.error("Failed to build notification email: %s", exc)
            return False

    # ── Message builders ─────────────────────────────────────────────────────

    def _build_message(self, jobs: List[dict]) -> MIMEMultipart:
        today = date.today().isoformat()
        subject = self._cfg.subject_template.replace("{date}", today)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self._cfg.from_address
        msg["To"] = self._cfg.to_address

        plain = self._build_plain_text(jobs, today)
        html = self._build_html(jobs, today)

        msg.attach(MIMEText(plain, "plain", "utf-8"))
        msg.attach(MIMEText(html, "html", "utf-8"))
        return msg

    def _build_plain_text(self, jobs: List[dict], today: str) -> str:
        lines = [
            f"Hi,",
            f"",
            f"The following {len(jobs)} job(s) require manual application:",
            f"",
        ]
        for i, job in enumerate(jobs, 1):
            location = job.get("location") or "Location not specified"
            reason = job.get("skip_reason") or "External application portal"
            lines += [
                f"{i}. {job.get('title', 'Unknown Title')} — {job.get('company', 'Unknown Company')} ({location})",
                f"   {job.get('url', '')}",
                f"   Reason: {reason}",
                f"",
            ]
        lines += [
            "---",
            f"Generated by job-applicator on {today}",
        ]
        return "\n".join(lines)

    def _build_html(self, jobs: List[dict], today: str) -> str:
        rows = ""
        for job in jobs:
            location = job.get("location") or "—"
            reason = job.get("skip_reason") or "External application portal"
            url = job.get("url", "")
            title = job.get("title", "Unknown Title")
            company = job.get("company", "Unknown Company")
            rows += (
                "<tr>"
                f"<td style='padding:8px;border-bottom:1px solid #eee'>"
                f"<a href='{url}' style='color:#0073b1;text-decoration:none'>{title}</a>"
                f"</td>"
                f"<td style='padding:8px;border-bottom:1px solid #eee'>{company}</td>"
                f"<td style='padding:8px;border-bottom:1px solid #eee'>{location}</td>"
                f"<td style='padding:8px;border-bottom:1px solid #eee'>{reason}</td>"
                "</tr>"
            )

        return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;color:#333;max-width:800px;margin:0 auto;padding:20px">
  <h2 style="color:#0073b1">Jobs Requiring Manual Application</h2>
  <p>{len(jobs)} job(s) could not be auto-applied to and need your attention:</p>
  <table style="width:100%;border-collapse:collapse;font-size:14px">
    <thead>
      <tr style="background:#f3f2ef">
        <th style="padding:10px;text-align:left;border-bottom:2px solid #ddd">Title</th>
        <th style="padding:10px;text-align:left;border-bottom:2px solid #ddd">Company</th>
        <th style="padding:10px;text-align:left;border-bottom:2px solid #ddd">Location</th>
        <th style="padding:10px;text-align:left;border-bottom:2px solid #ddd">Reason</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>
  <p style="color:#888;font-size:12px;margin-top:20px">
    Generated by job-applicator on {today}
  </p>
</body>
</html>"""

    # ── SMTP sender ──────────────────────────────────────────────────────────

    def _send(self, msg: MIMEMultipart) -> bool:
        cfg = self._cfg
        try:
            if cfg.smtp_port == 465:
                with smtplib.SMTP_SSL(cfg.smtp_host, cfg.smtp_port) as server:
                    server.login(cfg.smtp_user, cfg.smtp_password)
                    server.sendmail(cfg.from_address, cfg.to_address, msg.as_string())
            else:
                with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port) as server:
                    server.ehlo()
                    server.starttls()
                    server.ehlo()
                    server.login(cfg.smtp_user, cfg.smtp_password)
                    server.sendmail(cfg.from_address, cfg.to_address, msg.as_string())

            logger.info(
                "Notification email sent to %s (%d jobs).",
                cfg.to_address,
                len(msg.get_payload()),
            )
            return True

        except smtplib.SMTPAuthenticationError:
            logger.error(
                "SMTP authentication failed. Check smtp_user/smtp_password in config. "
                "For Gmail, use an App Password: https://myaccount.google.com/apppasswords"
            )
            return False
        except smtplib.SMTPException as exc:
            logger.error("SMTP error while sending notification: %s", exc)
            return False
        except OSError as exc:
            logger.error(
                "Network error connecting to %s:%d — %s",
                cfg.smtp_host,
                cfg.smtp_port,
                exc,
            )
            return False
